import * as fs from 'fs';
import * as path from 'path';
import { createDefaultConfig } from '../utils/config';

interface InitOptions {
  github?: boolean;
}

export function initCommand(options: InitOptions): void {
  const cwd = process.cwd();

  console.log('\n🚀 Initializing Baseline configuration...\n');

  // Create .baselinerc.json
  createDefaultConfig(cwd);

  // Create GitHub Actions workflow if requested
  if (options.github) {
    createGitHubWorkflow(cwd);
  }

  console.log('✅ Initialization complete!\n');

  if (options.github) {
    console.log('📝 Next steps:');
    console.log('   1. Review .github/workflows/baseline.yml');
    console.log('   2. Commit and push changes');
    console.log('   3. Create a pull request to see Baseline checks in action\n');
  }
}

function createGitHubWorkflow(projectPath: string): void {
  const workflowDir = path.join(projectPath, '.github', 'workflows');
  const workflowPath = path.join(workflowDir, 'baseline.yml');

  // Create .github/workflows directory if it doesn't exist
  if (!fs.existsSync(workflowDir)) {
    fs.mkdirSync(workflowDir, { recursive: true });
  }

  const workflowContent = `name: Baseline Compliance Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  baseline-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Baseline CLI
        run: npm install -g @edziocodes/baseline-cli

      - name: Run Baseline scan
        run: baseline scan --format json

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: baseline-report
          path: baseline-report.json

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'baseline-report.json';

            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));

              const complianceRate = report.totalFeatures > 0
                ? ((report.baselineCompliant / report.totalFeatures) * 100).toFixed(1)
                : '100.0';

              const body = [
                '## 📊 Baseline Compliance Report',
                '',
                \`**Files scanned:** \${report.totalFiles}\`,
                \`**Features detected:** \${report.totalFeatures}\`,
                '',
                \`✅ **Baseline compliant:** \${report.baselineCompliant}\`,
                \`⚠️ **Limited support:** \${report.limitedSupport}\`,
                \`🧪 **Experimental:** \${report.experimental}\`,
                '',
                \`**Compliance rate:** \${complianceRate}%\`,
                '',
                '---',
                '*Generated by [Baseline CLI](https://github.com/gaiborjosue/baseline-cli)*'
              ].join('\\n');

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
`;

  fs.writeFileSync(workflowPath, workflowContent);
  console.log(`✅ Created GitHub Actions workflow at ${workflowPath}`);
}
